- id: bolt-validate
  additional_dependencies: ['puppet']
  description: Validate syntax of Bolt plans
  entry: bolt-validate
  files: plans/\w+\.pp$
  language: ruby
  name: Validate Bolt plans

- id: epp-validate
  additional_dependencies: ['puppet']
  description: Validate syntax of Puppet EPP templates
  entry: epp-validate
  files: \.epp$
  language: ruby
  name: Validate EPP templates

- id: erb-validate
  description: Validate syntax of Ruby ERB templates
  entry: erb-validate
  files: \.erb$
  language: ruby
  name: Validate ERB templates

- id: g10k-validate
  description: Validate syntax of Puppetfile using g10k
  entry: g10k-validate
  files: Puppetfile$
  language: ruby
  name: Validate g10k Puppetfile

- id: puppet-lint
  additional_dependencies: ['puppet-lint']
  description: Check Puppet manifests for stylistic problems
  entry: puppet-lint
  files: \.pp$
  language: ruby
  name: puppet-lint

- id: puppet-validate
  additional_dependencies: ['puppet']
  description: Validate syntax of Puppet manifests
  entry: puppet-validate
  files: \.pp$
  exclude: plans/
  language: ruby
  name: Validate Puppet manifests

- id: puppet-strings
  additional_dependencies: ['puppet-strings']
  description: Validate puppet documentation is up to date
  entry: puppet-strings
  files: \.pp$
  language: ruby
  name: Validate puppet documentation

- id: r10k-validate
  additional_dependencies: ['r10k']
  description: Validate syntax of Puppetfile using r10k
  entry: r10k-validate
  files: Puppetfile$
  language: ruby
  name: Validate r10k Puppetfile

- id: ruby-validate
  additional_dependencies: ['ruby']
  description: Validate syntax of ruby code
  entry: ruby-validate
  files: \.rb$
  language: ruby
  name: Validate ruby syntax
