#!/usr/bin/env bash
set -eu

status=0
for path in "$@"; do
	output=$(puppet epp validate "$path" 2>&1) || {
		echo -e "\033[31m\033[1m$path: failed epp validation\033[0m"
		echo "$output"
		status=1
	}
done

exit "$status"
